"""Figures and tables for the paper, rendered from ``results/*.json`` only (no hand edits).

Table numbers follow the build plan's list (II, III, V, VI, VII). The paper itself is not in
the repository, so the mapping below was inferred from the plan and must be checked against
the paper text when the tables are pasted in.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from certex.bench.experiments import RESULTS


def _load(results_dir: Path, name: str) -> dict[str, Any] | None:
    path = results_dir / f"{name}.json"
    if not path.exists():
        return None
    data: dict[str, Any] = json.loads(path.read_text())
    return data


def _cell(c: Any) -> str:
    if c is None:
        return ""
    if c == "":
        return "ε"
    return str(c).replace("|", "\\|")


def _md(headers: list[str], rows: list[list[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(_cell(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def _fmt(x: float | None, digits: int = 4) -> str:
    return "n/a" if x is None else f"{x:.{digits}g}"


def render_figures(results_dir: Path) -> list[str]:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    made: list[str] = []
    e3 = _load(results_dir, "e3_attack_runtime")
    if e3 is not None:
        series = e3["rows"]["series"]
        fig, ax = plt.subplots(figsize=(5.5, 3.6))
        cp = [(r["length"], r["cpython_s"]) for r in series if r["cpython_s"]]
        ce = [(r["length"], r["certex_s"]) for r in series]
        if cp:
            ax.plot(*zip(*cp, strict=True), "o-", label="CPython re")
        ax.plot(*zip(*ce, strict=True), "s-", label="CERTEX kernel")
        ax.set_yscale("log")
        ax.set_xlabel("attack length (characters)")
        ax.set_ylabel("match time (s, log scale)")
        ax.set_title(r"$(a+)+\$$ on $a^k b$")
        ax.legend()
        ax.grid(True, which="both", alpha=0.3)
        fig.tight_layout()
        fig.savefig(results_dir / "fig2.png", dpi=160)
        plt.close(fig)
        made.append("fig2.png <- e3_attack_runtime.json rows.series[length, cpython_s, certex_s]")
    e4 = _load(results_dir, "e4_compile_overhead")
    if e4 is not None:
        sizes = [int(k) for k in e4["summary"]]
        mean = [e4["summary"][str(k)]["mean_ms"] for k in sizes]
        worst = [e4["summary"][str(k)]["worst_ms"] for k in sizes]
        fig, ax = plt.subplots(figsize=(5.5, 3.6))
        ax.plot(sizes, mean, "o-", label="mean")
        ax.plot(sizes, worst, "s--", label="worst")
        ax.set_xlabel("target IR size m")
        ax.set_ylabel("compile time (ms)")
        ax.legend()
        ax.grid(True, alpha=0.3)
        fig.tight_layout()
        fig.savefig(results_dir / "fig3.png", dpi=160)
        plt.close(fig)
        made.append("fig3.png <- e4_compile_overhead.json summary[size].mean_ms / worst_ms")
    return made


def render_tables(results_dir: Path) -> tuple[str, list[str]]:
    parts = ["# CERTEX results tables",
             "",
             "Generated by `certex bench figures` from `results/*.json`; do not edit by hand.",
             ("D1 is now 14 EXP / 10 POLY / 19 LIN (was 14 / 9 / 20): `x*.*x*$` was relabelled "
              "POLY after CPython took 3.7 s on a 1,603-character input (TRD v1.1 §B.7 row 1)."),
             ("Table numbering is inferred from the build plan (II, III, V, VI, VII); verify "
              "against the paper."),
             ""]
    trace: list[str] = []

    e1 = _load(results_dir, "e1_detection")
    if e1 is not None:
        counts: dict[str, int] = {}
        for r in e1["rows"]:
            counts[r["label"]] = counts.get(r["label"], 0) + 1
        parts += ["## Table II: D1 benchmark composition", "",
                  _md(["label", "patterns"], [[k, counts[k]] for k in ("EXP", "POLY", "LIN")]),
                  "", "Source: `e1_detection.json` rows[].label", ""]
        trace.append("Table II <- e1_detection.json rows[].label (counts)")
        names = {"star_height": "star height >= 2", "certex_none": "CERTEX (profile none)",
                 "certex_cpython": "CERTEX (profile cpython)"}
        rows = []
        timing = _load(results_dir, "e1_timing_baseline")
        if timing is not None:
            s = timing["summary"]
            rows.append(["base paper timing (grep -E)", s["tp"], s["fp"], s["fn"], s["tn"],
                         s["accuracy"], s["precision"], s["recall"], s["f1"]])
            trace.append("Table V timing row <- e1_timing_baseline.json summary")
        for key, label in names.items():
            s = e1["summary"][key]
            rows.append([label, s["tp"], s["fp"], s["fn"], s["tn"], s["accuracy"],
                         s["precision"], s["recall"], s["f1"]])
            trace.append(f"Table V {label} <- e1_detection.json summary.{key}")
        parts += ["## Table V: detection on D1", "",
                  _md(["method", "TP", "FP", "FN", "TN", "accuracy", "precision", "recall",
                       "F1"], rows),
                  "", "Source: `e1_detection.json` summary.*, `e1_timing_baseline.json` summary", ""]

    e2 = _load(results_dir, "e2_types")
    if e2 is not None:
        rows = [[c, v["correct"], v["total"], v["recall"]]
                for c, v in e2["summary"]["recall_by_class"].items()]
        rows.append(["all", e2["summary"]["correct"], e2["summary"]["total"],
                     round(e2["summary"]["correct"] / e2["summary"]["total"], 4)])
        parts += ["## Table III: type inference on D2", "",
                  _md(["class", "correct", "total", "recall"], rows),
                  "", "Source: `e2_types.json` summary.recall_by_class, summary.correct/total", ""]
        trace.append("Table III <- e2_types.json summary.recall_by_class")

    e3 = _load(results_dir, "e3_attack_runtime")
    if e3 is not None:
        rows = [[r["pattern"], r["length"], r["kernel"],
                 "hung (>30 s)" if r["cpython_hung"] else _fmt(r["cpython_s"]),
                 _fmt(r["certex_s"]), r["certex_steps"]] for r in e3["rows"]["patterns"]]
        parts += ["## Table VI: attack runtime, CPython vs CERTEX kernel", "",
                  _md(["pattern", "length", "kernel", "CPython (s)", "CERTEX (s)",
                       "CERTEX steps"], rows),
                  "", "Source: `e3_attack_runtime.json` rows.patterns[]", ""]
        trace.append("Table VI <- e3_attack_runtime.json rows.patterns[]")

    e4 = _load(results_dir, "e4_compile_overhead")
    if e4 is not None:
        rows = [[k, v["patterns"], _fmt(v["mean_ms"]), _fmt(v["worst_ms"])]
                for k, v in e4["summary"].items()]
        parts += ["## Table VII: compile overhead by pattern size", "",
                  _md(["target m", "patterns", "mean (ms)", "worst (ms)"], rows),
                  "", "Source: `e4_compile_overhead.json` summary[size]", ""]
        trace.append("Table VII <- e4_compile_overhead.json summary[size]")

    e5 = _load(results_dir, "e5_differential")
    if e5 is not None:
        s = e5["summary"]
        rows = [[m, v["cases"], v["disagreements"]] for m, v in s["per_mode"].items()]
        rows.append(["total", s["cases"], s["disagreements"]])
        parts += ["## Differential test (E5)", "",
                  _md(["mode", "cases", "disagreements"], rows),
                  "", "Source: `e5_differential.json` summary.per_mode", ""]
        trace.append("E5 table <- e5_differential.json summary.per_mode")

    e6 = _load(results_dir, "e6_d5")
    if e6 is not None:
        rows = [[r["pattern"], r["base_label"], r["raw_type"], r["normalised_type"],
                 r["class"], r["degree"], r["kernel"]] for r in e6["rows"]]
        parts += ["## D5: the base paper's cases (E6)", "",
                  _md(["pattern", "base label", "raw type", "normalised", "class", "degree",
                       "kernel"], rows),
                  "", "Source: `e6_d5.json` rows[]", ""]
        trace.append("E6 table <- e6_d5.json rows[]")

    e1b = _load(results_dir, "e1b_corpus")
    if e1b is not None:
        s = e1b["summary"]
        parts += ["## Public corpus (E1b)", "",
                  _md(["metric", "value"], [[k, v] for k, v in s.items()
                                            if not isinstance(v, (dict, list))]),
                  "", "Source: `e1b_corpus.json` summary", ""]
        trace.append("E1b table <- e1b_corpus.json summary")
    return "\n".join(parts) + "\n", trace


def render_all(results_dir: Path | None = None) -> str:
    out = results_dir or RESULTS
    lines = [f"figures: {m}" for m in render_figures(out)]
    text, trace = render_tables(out)
    (out / "tables.md").write_text(text)
    lines += [f"tables.md: {t}" for t in trace]
    return "\n".join(lines)
